### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by Charles-Hoot** [Dixith1196/THE-HUNT#1]
Not convinced that all of the fields are needed.  Is time spent required? Also not entirely sure how I would figure it out.

Not sure that the TeamPlayer needs to have any date besides the invite date ( along with a joined flag.)

**Comment by KHARIKA17** [comment]
Time spent is the Time taken to complete the competition by that particular Team.The other attributes like Date accepted Invite and Date rejected Invite and Date Left team attributes are required to track who is joining the team and who is leaving the team.

Please let us know if anything is not clear
