### ISSUE TITLE
Cost Estimate is confusing

### ISSUE THREAD

**Issue by Charles-Hoot** [Dixith1196/THE-HUNT#13]
There are hours per week determined, but it doesn't look like they transferred correctly to the cost estimate. There are lines in the cost estimate with hours but no billing.

I always wanted the hourly billing rate up front.

Without better numbers, I hesitate to look closer, but my sense is that you have not included enough time for implementation and testing.

**Comment by baskharm** [comment]
yeah, I have gone through the cost estimation table and I was able to detect the flaws in our cost estimation. I came up with the necessary corrections and updated the Readme.MD file.
